//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WulingWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PassengerVehicle
    {
        public string 时间 { get; set; }
        public string 国产进口 { get; set; }
        public string 省 { get; set; }
        public string 市 { get; set; }
        public string 县 { get; set; }
        public string 制造商 { get; set; }
        public string 车辆型号 { get; set; }
        public string 品牌 { get; set; }
        public string 车型 { get; set; }
        public string 排量 { get; set; }
        public string 变速器 { get; set; }
        public string 车辆类型 { get; set; }
        public string 车身型式 { get; set; }
        public string 燃油类型 { get; set; }
        public string 使用性质 { get; set; }
        public string 所有权 { get; set; }
        public string 抵押标记 { get; set; }
        public string 性别 { get; set; }
        public string 年龄 { get; set; }
        public string 车身颜色 { get; set; }
        public string 发动机型号 { get; set; }
        public string 功率 { get; set; }
        public string 排放标准 { get; set; }
        public string 轴距 { get; set; }
        public string 轮胎规格 { get; set; }
        public string 车外廓长 { get; set; }
        public string 车外廓宽 { get; set; }
        public string 车外廓高 { get; set; }
        public string 准确排量 { get; set; }
        public string 核定载客 { get; set; }
        public string 总质量 { get; set; }
        public string 整备质量 { get; set; }
        public string 轴数 { get; set; }
        public string 前轮距 { get; set; }
        public string 后轮距 { get; set; }
        public Nullable<int> 保有量 { get; set; }
        public System.Guid Id { get; set; }
    }
}
